
//----------------------------------------------------
// The following code was generated by CUP v0.10k
// Fri Aug 26 18:42:45 CEST 2022
//----------------------------------------------------

package rs.ac.bg.etf.pp1;

/** CUP generated class containing symbol constants. */
public class sym {
  /* terminals */
  public static final int DIVIDE = 27;
  public static final int MINUSDECR = 39;
  public static final int CONST = 7;
  public static final int EQUALS = 37;
  public static final int GRT = 31;
  public static final int GRTEQ = 32;
  public static final int NUMCONST = 52;
  public static final int LPAREN = 44;
  public static final int SEMI = 40;
  public static final int CONTINUE = 17;
  public static final int DOUBLE_QUESTION = 51;
  public static final int LESS = 33;
  public static final int MINUS = 25;
  public static final int RPAREN = 45;
  public static final int AND = 35;
  public static final int RECORD = 21;
  public static final int OR = 36;
  public static final int COMMA = 42;
  public static final int CLASS = 4;
  public static final int LSQRD = 46;
  public static final int PLUS = 24;
  public static final int MULTIPLY = 26;
  public static final int IF = 8;
  public static final int THIS = 18;
  public static final int DOT = 43;
  public static final int EOF = 0;
  public static final int RETURN = 14;
  public static final int SUPER = 19;
  public static final int NEW = 11;
  public static final int error = 1;
  public static final int NUMBER = 22;
  public static final int NEQ = 30;
  public static final int BREAK = 3;
  public static final int IDENT = 23;
  public static final int VOID = 15;
  public static final int EQ = 29;
  public static final int ERROR = 50;
  public static final int LBRACE = 48;
  public static final int ELSE = 6;
  public static final int ENUM = 5;
  public static final int READ = 13;
  public static final int GOTO = 20;
  public static final int CHARCONST = 53;
  public static final int WHILE = 10;
  public static final int RSQRD = 47;
  public static final int RBRACE = 49;
  public static final int PLUSINCR = 38;
  public static final int BOOLCONST = 54;
  public static final int EXTENDS = 16;
  public static final int PROG = 2;
  public static final int LESSEQU = 34;
  public static final int MODUO = 28;
  public static final int TWODOTS = 41;
  public static final int PRINT = 12;
  public static final int DO = 9;
}

