
//----------------------------------------------------
// The following code was generated by CUP v0.10k
// Thu Mar 31 15:52:41 CEST 2022
//----------------------------------------------------

package rs.ac.bg.etf.pp1;

/** CUP generated class containing symbol constants. */
public class sym_old {
  /* terminals */
	
	// kljucne reci
	
	public static final int PROG = 1;
	public static final int BREAK = 2;
	public static final int CLASS = 3;
	public static final int ENUM = 4;
	public static final int ELSE = 5;
	public static final int CONST = 6;
	public static final int IF = 7;
	public static final int DO = 8;
	public static final int WHILE = 9;
	public static final int NEW = 10;
	public static final int PRINT = 11;
	public static final int READ = 12;
	public static final int RETURN = 13; 
	public static final int VOID = 14; 
	public static final int EXTENDS = 15;
	public static final int CONTINUE = 16;
	public static final int THIS = 17;
	public static final int SUPER = 18;
	public static final int GOTO = 19;
	public static final int RECORD = 20; 
	
	// vrste tokena
	
	public static final int IDENT = 21;
	public static final int LETTER = 22; 
	public static final int NUMCONST = 23;
	public static final int CHARCONST = 24;
	public static final int PRINTABLECHAR = 25;
	public static final int BOOLCONST = 26;
	
	// operatori
	
	public static final int PLUS = 27;
	public static final int MINUS = 28; 	
	public static final int MULTIPLY = 29; // fali 30 nmg sad 
	public static final int DIVIDE = 31; 
	public static final int MODUO = 32; 
	public static final int EQ = 33; 
	public static final int NEQ = 34; 
	public static final int GRT = 35;
	public static final int GRTEQ = 36; 
	public static final int LESS = 37; 
	public static final int LESSEQU = 38; 
	public static final int AND = 39; 
	public static final int OR = 40; 
	public static final int EQUALS = 41; 
	public static final int PLUSINCR = 42; 
	public static final int MINUSDECR = 43; 
	public static final int SEMI = 44;
	public static final int TWODOTS = 45;
	public static final int COMMA = 46;
	public static final int DOT = 47;
	public static final int LPAREN = 48;
	public static final int RPAREN = 49;
	public static final int LSQRD = 50;
	public static final int RSQRD = 51;
	public static final int LBRACE = 52;
	public static final int RBRACE = 53;
	
	// ostalo
	
	public static final int EOF = 54;
	public static final int ERROR = 55;
}

